### ISSUE TITLE
Howto read the SMTP server response?

### ISSUE THREAD

**Issue by rdeavila** [emersion/go-smtp#102]
Hi!

How do I read the SMTP server response on `smtp.SendMail` ? Example: my SMTP server tell me the queue id when the email is queued (`250 2.0.0 Ok: queued as C0E5C82029\n`). I want to get this.

IT's possible?

**Comment by emersion** [comment]
No, it's not possible right now.

Note that the status is just plain-text, so it would only be useful for debugging.

**Comment by gowthamgts** [comment]
@emersion - there are some cases where we will do custom logic on top of the response to support suppression. so no plans to include this in the future?
