### ISSUE TITLE
How to send reply to same thread?

### ISSUE THREAD

**Issue by DeadNumbers** [emersion/go-smtp#105]
I'm get Message-ID from imap 
```Golang
    mr, _ := mail.CreateReader(r)
    header := mr.Header
    msgId, _ = header.MessageID()
```
and build new message:
```Golang
    msg.SetHeader("In-Reply-To", msgId)
    msg.SetHeader("References", msgId)
    msg.SetHeader("From", login)
    msg.SetHeader("To", "myaccount@gmail.com")
```
This email is not displayed in the correspondence thread, it is visible as a new email. How to send email in thread?

**Comment by emersion** [comment]
The format for the `In-Reply-To` header is `"<" + msgID + ">"`.

Related: https://github.com/emersion/go-message/pull/72
