### ISSUE TITLE
`Backend` interface should not return `Session` which is used by smtp client

### ISSUE THREAD

**Issue by iredmail** [emersion/go-smtp#124]
Dear developers,

Currently `Backend` interface requires 2 methods as defined:

```
type Backend interface {
	Login(...omit...) (Session, error)
	AnonymousLogin(...omit...) (Session, error)
}
```

But methods required by `Session` interfaces are all used by smtp client. Should we add a new session type used by server instead and replace the one used by smtp client? For example:

```
type ServerSession interface {
    ...
}

type Backend interface {
	Login(...omit...) (ServerSession, error)
	AnonymousLogin(...omit...) (ServerSession, error)
}
```

**Comment by emersion** [comment]
>But methods required by Session interfaces are all used by smtp client.

Do you mean that some of the `Session` methods have the same name as the `Client` methods? How is this an issue?

**Comment by iredmail** [comment]
I don't mean it's an issue. Just want it to be accurate.

```
type Session interface {
	Reset()
	Logout() error
	Mail(from string, opts MailOptions) error
	Rcpt(to string) error
	Data(r io.Reader) error
}
```

A SMTP server doesn't do any of them, so require to define them all for a session used by smtp server doesn't make much sense.

**Comment by emersion** [comment]
>A SMTP server doesn't do any of them

I don't understand what you mean.

**Comment by foxcpp** [comment]
> A SMTP server doesn't do any of them, so require to define them all for a session used by smtp server doesn't make much sense.

Backend implements all of these operations and they are used by SMTP server.
Session object is not used by client in any way. You must have understood the library interface.

**Comment by iredmail** [comment]
Checked source code and seems my mistake. I thought it was same as the smtp commands. Sorry about the noise. :)

**Comment by emersion** [comment]
Pushed cb448239d67e to document `Session`.

**Comment by iredmail** [comment]
This sentence makes it clear: `// The methods are called when the remote client issues the matching command.`
Thanks. :)
