### ISSUE TITLE
Check line length code valid ? 

### ISSUE THREAD

**Issue by chmike** [emersion/go-smtp#126]
The file `lengthlimit_reader.go` contains the function `func (r lineLimitReader) Read(b []byte)`.
Shouldn't the receiver be passed as pointer instead of value copy ?

The function is modifying `r`, but when the receiver is a value instead of a pointer, that modification is discarded on return. 

This possible bug would have been detected with unit testing.

**Comment by foxcpp** [comment]
Interestingly that the code still works likely because a single read is always (?) bigger than max line length due to buffer. But lets fix that anyway. Thanks for reporting!
