### ISSUE TITLE
rcpt: parameter sent to "Rcpt" function removes mail addr formatting

### ISSUE THREAD

**Issue by mrvik** [emersion/go-smtp#128]
[`conn.go`](https://github.com/emersion/go-smtp/blob/c36845b67b04d31ac44be06ef9b62e07f0825d54/conn.go#L487) removes address formatting before calling `Rcpt (to string)` interface function, so the function cannot use [`mail.ParseAddress`](https://pkg.go.dev/net/mail#ParseAddress) to parse address.

I can think two options to "fix" this, one is breaking (as it requires changing interface) and the other is not so breaking (but may require changes on implementations)

* Option 1 (breaking): pass `*mail.Address` to `Rcpt` interface function. This is the most logic option so interface implementations don't parse protocol-specific addresses and settle with go-specific parameters.
* Option 2 (not-so-breaking): don't modify the interface, but send mail address as-is (w/o the "to:" part) to `Rcpt`. This leaves on interface implementations the address parsing logic (most of them will just call `mail.ParseAddress`). This leaves the door open to bad addresses on Rcpt command being ignored (as they're not being parsed at all)

~For me, the best option is the 1st bc it removes protocol-specific logic from interface, but may break existing implementations.~

Edit: A closer look reveals smtp logic is handled there, but `net/mail` is not imported, so maybe falling back to interface parsing the message is the point of `conn.go`

**Comment by emersion** [comment]
I'm a little bit confused because [the tests](https://github.com/emersion/go-smtp/blob/c36845b67b04d31ac44be06ef9b62e07f0825d54/server_test.go#L473) don't contain any special handling for `TO:` and pass just fine. In other words:

```
RCPT TO: <root@example.org>
```

results in the string "root@example.org" being passed to the backend.

**Comment by mrvik** [comment]
Yes, mails w/o "<>" work as well as mails "<mail@foo.bar>", but if you add a name like "Foo Bar <foo@bar.org>", the function breaks

**Comment by mrvik** [comment]
Consider this patch on test:
```diff
diff --git a/server_test.go b/server_test.go
index f2bfe9f..d25e6cd 100644
--- a/server_test.go
+++ b/server_test.go
@@ -443,7 +443,7 @@ func TestServer(t *testing.T) {
 		t.Fatal("Invalid MAIL response:", scanner.Text())
 	}
 
-	io.WriteString(c, "RCPT TO:<root@gchq.gov.uk>\r\n")
+	io.WriteString(c, "RCPT TO:Someone <root@gchq.gov.uk>\r\n")
 	scanner.Scan()
 	if !strings.HasPrefix(scanner.Text(), "250 ") {
 		t.Fatal("Invalid RCPT response:", scanner.Text())
```

**Comment by emersion** [comment]
>but if you add a name like `Foo Bar <foo@bar.org>`

Is this allowed by the RFC? Looking at [the RFC](https://tools.ietf.org/html/rfc5321#section-4.1.1.3), it doesn't seem like it.

**Comment by mrvik** [comment]
OMG, I was mixing 2822 data and 5321 :exploding_head: 

Ok, so everything is good, sorry
