### ISSUE TITLE
Add LMTP support

### ISSUE THREAD

**Issue by SirCmpwn** [emersion/go-smtp#13]
https://en.wikipedia.org/wiki/Local_Mail_Transfer_Protocol

LMTP is not much different from SMTP. The main differences are:

- Needs to be able to listen on a Unix socket
- EHLO -> LHLO
- LMTP servers have no queues and make the final call to accept or reject a message in a single transaction

**Comment by emersion** [comment]
* After a DATA command, one status reply is sent per RCPT TO

Also:

> The server SHOULD send each reply as soon as possible.

**Comment by SirCmpwn** [comment]
Thanks!
