### ISSUE TITLE
Get client IP address while client connects to smtp server?

### ISSUE THREAD

**Issue by iredmail** [emersion/go-smtp#130]
Dear @emersion

First of all, thanks for the great work. 👍 

We're trying to implement an internal SMTP server, and we'd like to reject client as earlier as possible if client IP address is not whitelisted. Currently it's ok to get client IP in `Mail()` method of [`Session` interface](https://pkg.go.dev/github.com/emersion/go-smtp#Session), but we'd like to reject it even earlier. For example, when the client connects to the smtp server.

Could you share some idea of how we can achieve this? Thank you. :)

**Comment by emersion** [comment]
Maybe we could add a `Serve.ServeConn(c net.Conn)` function like `x/net/http2` has? An alternative would be to add hooks to the `Server` configuration like `net/http` has.

Note, you should already be able to do this by implementing a custom `net.Listener` that filters incoming connections, however it's somewhat boilerplate-y.

**Comment by iredmail** [comment]
1. Is it better to add a new method for the `Backend` struct? e.g. `Connect()`, it's called when client connected.
1. Another question: How to send reply to client like `conn.WriteResponse()`? i mistakenly used `return &smtp.SMTPError{...}` even it returns `200` smtp code, client considers it's a failure. :(

**Comment by Savageman** [comment]
Sorry to intrude, But I'm interested in the same kind of feature for the `Helo` command, if it can help.

The session is not yet created at connection time (neither `Login()` or `AnonymousLogin()` was called). Maybe this hook to the `Backend` interface instead?

**Comment by emersion** [comment]
Can you open a new issue an explain your use-case?

**Comment by foxcpp** [comment]
There is no way to terminate the connection on NewSession though. That's probably can be done via #147. Needs discussion.

**Comment by emersion** [comment]
Wouldn't an error returned by `NewSession` terminate the connection?

**Comment by foxcpp** [comment]
It will return an error response to the client without terminating the connection. Client can issue EHLO/HELO/QUIT in this case.
