### ISSUE TITLE
Add a way to hook into the HELO commands

### ISSUE THREAD

**Issue by Savageman** [emersion/go-smtp#136]
Similar to #130, a hook to the HELO commands can be useful to implement security depending on the value of the argument provided.

Examples: check the domain syntax, its existence, whether it's correctly configured to accept emails, etc.

**Comment by foxcpp** [comment]
Possibly relevant: https://github.com/emersion/go-smtp/pull/114#issuecomment-663433397  https://github.com/emersion/go-smtp/pull/114#issuecomment-663457679

**Comment by emersion** [comment]
Indeed. Seems like it would make sense to just do what your comment says.

**Comment by foxcpp** [comment]
With the recent backend interface change, NewSession runs on HELO/EHLO.
