### ISSUE TITLE
Add an ability to disable the client's lineLimitReader

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#138]
For server you can specify `MaxLineLength = 0`, but it is hardcoded for the client:

https://github.com/emersion/go-smtp/blob/ca8725c98f1c5a49f93efa09c6d7d7bfce135c6e/client.go#L127

**Comment by emersion** [comment]
What's the use-case for this?

**Comment by kayrus** [comment]
I'd like to align this functionality with server options and avoid issues, when remote server responds with a line greater than 2000 chars.

**Comment by emersion** [comment]
I'd prefer not to add this unless someone hits the issue in practice. Servers aren't supposed to send long lines.

**Comment by foxcpp** [comment]
FYI This limit is already 2x of what RFC allows.
If we implement BINARYMIME/CHUNKING client - we can temporarily disable it while handling the BDAT command.

**Comment by emersion** [comment]
But the limit is for the data we receive, not the data we send, right? So shouldn't be an issue in any case?

**Comment by foxcpp** [comment]
Oh, you are right. Nevermind then.
