### ISSUE TITLE
No milter support?

### ISSUE THREAD

**Issue by markdingo** [emersion/go-smtp#141]
Not necessarily an issue, but I'm curious as to why the server side of this package doesn't use https://github.com/emersion/go-milter/

It seems like a fairly obvious match to me, but I'm new to both packages, so it's likely I'm missing something.

**Comment by foxcpp** [comment]
Why would it? This is not a complete server implementation, if you need it-you can integrate milter in your backend code.

**Comment by markdingo** [comment]
When you say "this is not a complete server implementation" I guess I was under the impression that it was. What sort of server implementation is it then? A toy one? An experimental one?

The project documentation doesn't really make it clear that this isn't a serious server implementation. My mistake for thinking so.

**Comment by emersion** [comment]
This is a library for SMTP servers. The term "library" is included in the project summary.
