### ISSUE TITLE
How do I send emails directly from this smtp server, as per the example ?

### ISSUE THREAD

**Issue by alkanna** [emersion/go-smtp#142]
I ran the example and as far as I can see, what I send to the SMTP server gets logged to stdout, but what happens after that ?
Is there some additional logging I'm not aware of ?
I tried delivering emails to temporary email services, but it seems it never reaches the inbox.
Am I missing something ?

Thanks and sorry for what is probably a pretty stupid question :)

**Comment by emersion** [comment]
This isn't a full mail server, it's just a mail server library.

**Comment by alkanna** [comment]
@emersion I'm sorry but that is not very clear, then if I may ask, what else would need to be implemented in order to get emails to be delivered ?

**Comment by emersion** [comment]
You're looking for a full email server, like postfix or maddy. go-smtp isn't what you're looking for.
