### ISSUE TITLE
Distinguish server and client debug logs 

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#144]
Currently the debug mode writes all the input and output into one stream:

https://github.com/emersion/go-smtp/blob/26eb4814e227ff64ec3316910eb0b4e357e6e4e7/conn.go#L84-L85

I'd like to have independent debug streams and alternatively skip or mask `AUTH` command details.

Probably it's also worth adding an error handler inside the `WriteResponse` method, e.g. `ResponseLog` but not in server, but connection scope to have an ability to specify the requestID/connectionID.

**Comment by kayrus** [comment]
@emersion something like this for sessions logging: https://gist.github.com/kayrus/860c1e9d522e382fcf0b6b8f420017b9

**Comment by kayrus** [comment]
Another use case is to catch stale connection events, when `AUTH` was done but the rest wasn't, and a connection was timed out.

**Comment by emersion** [comment]
Sorry, but I'll close this as out-of-scope. The `DebugWriter` functionality was never meant to be a way for library users to add more functionality, it's purely a debugging tool.
