### ISSUE TITLE
server: Allow to access underlying net.Conn

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-smtp#147]
My use-case is obtaining the full PROXY header from https://github.com/pires/go-proxyproto.

Lazy solution: Just add net.Conn into ConnectionState.
But I feel like getting rid of ConnectionState and just passing Conn to backend is 
a better idea. We then can just add Conn.Conn() method (and probably Conn.Hostname()).

**Comment by kayrus** [comment]
Do you want to be aware whether PROXY protocol is enabled for a connection?
May be related to #144, where I want to get flexibility for logging.
