### ISSUE TITLE
Add function to get connection RemoteAddr

### ISSUE THREAD

**Issue by webfrank** [emersion/go-smtp#15]
Hi,
   it would be useful to have the remote address of the connection to implement a filter based on sender IP.
  I think it could be implemented defining User struct (UserData as User is already ad interface) with RemoteAddr field filled during init of connection.
  
  This change will impact how User is defined as at this moment the Login functions are responsible of User creation. With this change the User object is created by the connection filling all relevant data and passing it to Login functions. Is this doable?

**Comment by emersion** [comment]
I've been thinking about this. Having access to `RemoteAddr` is indeed required for filters and SPF/DMARC.

I guess the best way to do this would be to add a new parameter to `Login` and `AnonymousLogin`. We could also add in a `TLS *tls.ConnectionState` field for TLS information. I'm not sure about the name though, maybe `LoginRequest` would be a better one? (For consistency with `http.Request`)

I'm okay with breaking the API, the package is explicitly marked as unstable. Are you willing to send a PR to add this feature?

**Comment by webfrank** [comment]
Hi,

     ok I'll work on this PR. I'll update you ASAP


Bye


Il 17/09/18 13:40, emersion ha scritto:

**Comment by ksinica** [comment]
Another way might be to make ```dataReader``` "hijackable". What I mean is to add ```Hijack()``` method, that will return underlying connection (like in ```net/http```):

```go
type dataReader struct {
    r.   io.Reader
    conn net.Conn
		
    limited bool
    n       int64
 }
		
 func (d *dataReader) Hijack() net.Conn {
     return d.conn
 }
```

It would be possible to get for ex. client remote address without breaking API:
```go
func (u *user) Send(from string, to []string, r io.Reader) error {
    type hijacker interface {
        Hijack() net.Conn
    }

    conn := r.(hijacker).Hijack()

    fmt.Println("Addr:", conn.RemoteAddr().String())
    
    // ...
}
```
What do you guys think?

**Comment by foxcpp** [comment]
It would also be nice to have access to the hostname reported in EHLO/HELO command. For server-server communication, we may want to check it against rDNS and actual IP of the peer.

IMO, it would be best to define a structure that contains all useful information about connection state and pass it to AnonymousLogin/Login as a third argument.
Say...
```go
type ConnInfo struct {
  Hostname string
  RemoteAddr net.Addr
  TLS *tls.ConnectionState
}
```
