### ISSUE TITLE
StartTLS handshake error breaks the connection

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#152]
v0.15.0

https://github.com/emersion/go-smtp/blob/ff30d701e1730f7d881af58a0762a878f541e1be/conn.go#L597-L600

The function doesn't return after the `WriteResponse` call, and the `c.conn` is assigned to invalid `tlsConn`.

Besides the `c.init()` command wraps the `c.server.Debug` twice (teereader and multiwriter), and as a result if your starttls connection is fine you'll get a mess in the debug log:

https://github.com/emersion/go-smtp/blob/ff30d701e1730f7d881af58a0762a878f541e1be/conn.go#L78-L88

**Comment by foxcpp** [comment]
Added missing `return` in the referenced commit. I am unable to confirm the issue with Debug writer - it does not wrap c.conn twice as wrapped connection is used in c.text, not c.conn.

**Comment by kayrus** [comment]
> it does not wrap c.conn twice as wrapped connection is used in c.text, not c.conn

you're right. It was too late, when I noticed a couple of issues, I might mixed up c.text and c.conn. Thanks for fixing my findings!
