### ISSUE TITLE
DialTimeout / Incorrect address(TLS)

### ISSUE THREAD

**Issue by Gusted** [emersion/go-smtp#155]
Hi!

# Feature request

So while using the go-smtp library, with note to `smtp.Dial` and `smtp.DialTLS` functions.
Their are no safe-guards in place that the passed `addr` is correct or even valid at all. Normally you could resolve this by adding a timeout to ensure you always get a response from the function, however this is currently not the case in `go-smtp`. Could this be added as an extra option or by de-facto default?

# Situation

Let's say I was using the alps mail server and my DNS wasn't configured right(real story).
Let's say I had specified an  `_submission` SRV instead of the correct  `_submission*s*`, alps would rightfully just call the `smtp.Dial` function instead of the correct `smtp.DialTS` function. This results in a deadlock of some sort because the Dial implementation of golang won't return any response(ever) and won't be cancelled because their are no timeouts specified.

Regards,
Gusted

**Comment by emersion** [comment]
Indeed, a default timeout sounds like a good idea. Callers can always use `NewClient` if they want to customize the dialing. I thought we already had that, but that may not be the case.

**Comment by Gusted** [comment]
I had a look, it seems like using `NewClient` with a timeout Dial is a good alternative. But indeed would be nice to have inside the library by standard, to avoid such kind of "deadlock" situations.
