### ISSUE TITLE
Add actual example in README

### ISSUE THREAD

**Issue by MichailVestnik** [emersion/go-smtp#159]
Hi! 

i copied your simple example from README and cannot use it. Official Go extension in VS Code find errors in server example.

If you can help me figure it out, I would be very grateful! 

![Снимок экрана от 2021-09-05 12-48-13](https://user-images.githubusercontent.com/87961969/132114478-f68a2fd9-2f13-43d3-a2c9-5b9b567533fa.png)
![Снимок экрана от 2021-09-05 12-48-23](https://user-images.githubusercontent.com/87961969/132114479-28ced7d9-21a3-4177-97c5-74681f9d8462.png)

Спасибо!

**Comment by iredmail** [comment]
The example in README is for upcoming 0.16.0, which is not backward compatible.

**Comment by MichailVestnik** [comment]
Thanks.
