### ISSUE TITLE
Customize error status and assign a message ID on success

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#160]
If an email processing is failed, the error message is confusing `Error: transaction failed, blame it on the weather`. There should be a way to customize it.

If an email is processed successfully, there should be a way to return a message ID, not only the `OK: queued`.

**Comment by emersion** [comment]
https://github.com/emersion/go-smtp/issues/131

**Comment by foxcpp** [comment]
It's been already discussed multiple times that there is little value in customization of success messages. Error messages can be customized by returning `SMTPError`.

**Comment by olljanat** [comment]
> there is little value in customization of success messages.

How about always generating message ID and returning that to client?

Example Postfix do reply with message like `2.0.0 Ok: queued as B8D891E0010` and at least in https://github.com/emersion/go-smtp/pull/132#issuecomment-749569128 repo owner seems to agreeing that matching with Postfix is good idea.

**Comment by endreszabo** [comment]
> How about always generating message ID and returning that to client?

(In my fork) I created an `Id` field in the `Conn` struct for the connections (and sub-id for the individual `Session`s) and I simply append this ID to all the messages returned with `writeResponse`. Exactly like how Google does.

I also log every SMTP transaction (except for the DATA payload itself), so the response on the wire is like:
{"cid":"b01264a880a7","transaction":1,"dir":"tx","time":"2025-10-06T12:50:18Z","message":"250 2.0.0 OK: queued with ID - b01264a880a7.1 gsmtp\r"}
