### ISSUE TITLE
server: Impossible to disable PLAIN auth

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#170]
PLAIN auth is enabled by default and it is not possible to disable it:

https://github.com/emersion/go-smtp/blob/30169acc42e795e5d35ce901c8387950b103dfd9/server.go#L86-L87

it also doesn't look correct that `Session` interface now requires the `AuthPlain` method (#146). Why doesn't it require other auth methods? Why don't rely on sasl auth methods defined explicitly?

**Comment by emersion** [comment]
go-imap v2's design: https://pkg.go.dev/github.com/emersion/go-imap/v2/imapserver#SessionSASL

**Comment by emersion** [comment]
https://github.com/emersion/go-smtp/pull/254 fixes this.
