### ISSUE TITLE
Possible race condition in dataReader's Read method

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#172]
Running an SMTP server with race detection (`go run -race`) showed a potential race condition in:

https://github.com/emersion/go-smtp/blob/30169acc42e795e5d35ce901c8387950b103dfd9/data.go#L67

and

https://github.com/emersion/go-smtp/blob/30169acc42e795e5d35ce901c8387950b103dfd9/data.go#L143

and

https://github.com/emersion/go-smtp/blob/30169acc42e795e5d35ce901c8387950b103dfd9/conn.go#L653

**Comment by foxcpp** [comment]
That seems to indicate that you have Read's on data reader running after Data completes which is not supported. I think we should update documentation to explicitly mention this.
