### ISSUE TITLE
SMTP client must have an ability to set greeting timeout

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#175]
There is only one way to initialize an SMTP client: `NewClient` function.
This function doesn't allow to set greetings timeout and it has hardcoded 5 minutes timeout, even if the underlying connection already has a deadline, it is being overwritten:

https://github.com/emersion/go-smtp/blob/30169acc42e795e5d35ce901c8387950b103dfd9/client.go#L104-L105

If there is a network issue and TCP connection is established, but server doesn't respond with a greeting due to some reasons, the client will hang for an uncontrolled period of time.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/go-smtp/pull/184
