### ISSUE TITLE
Add method for data headers in Session interface.

### ISSUE THREAD

**Issue by kmpm** [emersion/go-smtp#179]
This is a feature request that will require a breaking change to the Session interface.
I would like to extend the Session interface with yet another method `DataHeader(value string) error`
This in combination with changes to dataReader to enable it catch and return headers until the first empty line.
It could be solved in the Data method of the interface but since every single byte is checked in dataReader anyway I just thought it would be a good place to implement such a thing.

I have working code but I'd like to know if such a thing ever would be accepted before I go any further with test, documentation and such.

**Comment by emersion** [comment]
I don't understand your use-case.
