### ISSUE TITLE
Inetd activation

### ISSUE THREAD

**Issue by stephane-martin** [emersion/go-smtp#18]
Hello,

In classical inetd activation, inetd already "Accept"s the incoming connection from client, and then passes the accepted connection to the daemon.

In that case I need to bypass the Accept() call that happens in the Serve() method (server.go line 83).

Unfortunately the handleConn method is private, so I can't call it directly.

Hence my very small feature request: rname handleConn to HandleConn :)

Thanks,
Stephane

**Comment by stephane-martin** [comment]
Oh, and newConn too !

**Comment by emersion** [comment]
How is this handled with e.g. `net/http`?

**Comment by stephane-martin** [comment]
That's a very good question indeed.

I don't think that net/http has any special to handle inetd services.

But that pointed me in the right direction: wrap net.Listener and net.Conn to make the Accept() call a no-op.

https://gist.github.com/stephane-martin/57a19466633b7ce712945aaed7a0e751

Please be free to comment/propose something else!

**Comment by emersion** [comment]
Does this work? If so, this seems like a better idea.
