### ISSUE TITLE
Server.Serve exits even on temporary errors

### ISSUE THREAD

**Issue by drdaeman** [emersion/go-smtp#180]
Hey, thank you for this library! I was experimenting with custom net.Listeners and it seems that `Serve` exits on any error from `l.Accept` unconditionally:
https://github.com/emersion/go-smtp/blob/f9aa4f40ae7468273caf937f2742c36346de08a4/server.go#L113-L122

Unfortunately, this essentially causes server to shut down upon non-fatal errors. This potentially allows a DoS attack (shutting server down by maliciously closing connections as they're about to get accepted), although this is only my suspicion that I haven't properly validated. IIRC, TLS listener may return `net.ErrClosed` if something bad happens during the handshake, and even plain TCP connections may accidentally fail with `ECONNRESET` or `ECONNABORTED`. Either way, I believe a slightly more sophisticated loop would be an improvement.

Here's an adapted version based on [how net/http does it](https://github.com/golang/go/blob/00535b839841227ba60c2de78fbf767088f865bc/src/net/http/server.go#L3039-L3060):
```go
var tempDelay time.Duration // how long to sleep on accept failure

for {
	c, err := l.Accept()
	if err != nil {
		select {
		case <-s.done:
			// we called Close()
			return nil
		default:
		}
		if ne, ok := err.(net.Error); ok && ne.Temporary() {
			if tempDelay == 0 {
				tempDelay = 5 * time.Millisecond
			} else {
				tempDelay *= 2
			}
			if max := 1 * time.Second; tempDelay > max {
				tempDelay = max
			}
			s.ErrorLog.Printf("accept error: %v; retrying in %v", err, tempDelay)
			time.Sleep(tempDelay)
			continue
		}
		return err
	}
	go s.handleConn(newConn(c, s))
}
``` 
(Possibly somewhat contradictory, those errors are marked as "temporary" - see https://github.com/golang/go/issues/6163 for more details).

**Comment by emersion** [comment]
Indeed, we shouldn't exit on temporary `Accept` errors. Patches welcome!
