### ISSUE TITLE
why these  examples not working!

### ISSUE THREAD

**Issue by jeel2331** [emersion/go-smtp#186]
i installed necessary libraries and pasted the code from the read me file under server section and it gave me the below error 

`.\goApp.go:17:9: cannot use &Session{} (type *Session) as type smtp.Session in return argument:
        *Session does not implement smtp.Session (wrong type for Mail method)
                have Mail(string, *smtp.MailOptions) error
                want Mail(string, smtp.MailOptions) error
.\goApp.go:58:21: cannot use be (type *Backend) as type smtp.Backend in argument to smtp.NewServer:
        *Backend does not implement smtp.Backend (missing AnonymousLogin method)`

**Comment by emersion** [comment]
The examples in the README are for the latest commit, not for the latest release.

**Comment by YoungjuWang** [comment]
@jeel2331 

you can use example in certain tags

ex) https://github.com/emersion/go-smtp/blob/v0.15.0/README.md
