### ISSUE TITLE
Could you please support the authentification type of LOGIN?

### ISSUE THREAD

**Issue by MaoJianwei** [emersion/go-smtp#194]
Outlook server uses this authentification type: LOGIN
that is not support by golang official lib: net/smtp

**Comment by emersion** [comment]
Nope. LOGIN is a deprecated, non-standard mechanism.

**Comment by MaoJianwei** [comment]
I don't think so, @emersion 
Outlook server still use LOGIN.
126.com e-mail also uses LOGIN, which is the biggest e-mail provider in China.
