### ISSUE TITLE
No greeting when starting with `tls.Config`

### ISSUE THREAD

**Issue by ditschedev** [emersion/go-smtp#199]
Hey there.

I just started implementing a bulk messaging api relay server with your library and everything works smoothly.

But since a couple days ago, where I was setting up a testing environment I ran into problems. I am deploying my application in a docker container with a port forwarding at `587`.
In my code I gather certificates using [certmagic](https://github.com/caddyserver/certmagic). I can successfully obtain a certificate and get a populated `tls.Config` as described here: https://github.com/caddyserver/certmagic/blob/5deb7c2fb0e7ab1f1990cf21134f18cde7554ffc/config.go#L935

Now starting the smtp server using `ListenAndServeTLS()` works without any errors or problems, I just can't seem to connect to my relay. Either using

```
telnet relay.example.com 587

Trying x.x.x.x..
Connected to relay.example.com.
Escape character is '^]'.
```

or 

```
openssl s_client -starttls smtp -connect relay.example.com:587

CONNECTED(00000005)
```

the connection can be established but it seems like there is no tls handshake or anything really happening. It just hangs and I never get the greeting.

Here is my configuration:
```go
s := smtp.NewServer(be)
s.Addr = "0.0.0.0:" + viper.GetString("server.port")
s.Domain = viper.GetString("server.hostname")
s.ReadTimeout = 30 * time.Second
s.WriteTimeout = 30 * time.Second
s.MaxMessageBytes = viper.GetInt("server.maxMessageBytes")
s.MaxRecipients = viper.GetInt("server.maxRecipients")
s.AllowInsecureAuth = !viper.GetBool("le.enabled")
s.EnableAuth(sasl.Login, func(conn *smtp.Conn) sasl.Server {
    return sasl.NewLoginServer(func(username, password string) error {
	state := conn.State()
	session, err := be.Login(&state, username, password)
	if err != nil {
		return err
	}

	conn.SetSession(session)
	return nil
    })
})
return s
```

I was already thinking of proxying the connection through a L4 layer proxy which handles the encryption but I would prefer if the server could handle it by itself.

Help is fairly appreciated!

Cheers
ditschedev

**Comment by kayrus** [comment]
You mixed up SMTPS pure TLS protocol (usually 465 port) with StartTLS over plain SMTP (587).

To run server with StartTLS you need to use `ListenAndServe` method and `openssl s_client -starttls smtp -connect relay.example.com:587` should work fine.

**Comment by ditschedev** [comment]
Thanks @kayrus.
Yeah I got irretated. Reason for that was also, that trying smtps over 465 (though its deprecated) didn't work because of a mistake in the `GetCertificate` func in my `tls.Config`. Managed to fix it and StartTLS over SMTP now works like a charm!

**Comment by kayrus** [comment]
@ditschedev I wouldn't say that 465 is deprecated. It was in RFC-6409, but then this statement was revoked in the recent RFC-8314, see https://serverfault.com/a/957769/176975
