### ISSUE TITLE
Auth should be mandatory for `MAIL`, `RCPT` & `DATA` commands when `server.AuthDisabled` is `false`

### ISSUE THREAD

**Issue by mukulsib** [emersion/go-smtp#216]
In current scenario, user is able to send `MAIL`, `RCPT` & `DATA` commands even when `server.AuthDisabled=false`.

In below image attached, i did not do any auth but still i was able to issue commands.
<img width="178" alt="image" src="https://user-images.githubusercontent.com/84002732/227719845-fc80a764-edcb-4e4c-bcee-42604f9901c5.png">

I also found this [error](https://github.com/emersion/go-smtp/blob/master/backend.go#L8) declared for exact use case but it is not used any where except of the test cases. 
<img width="158" alt="image" src="https://user-images.githubusercontent.com/84002732/227720092-0ec2bda7-5c5c-4b09-8597-d6f4ce93ffe5.png">
Maybe the behaviour got broken with some change?

However this is highly unexpected and should be fixed as soon as possible, as we are currently blocked in our development. 

I don't know how others are handling this?

It should be handled exactly [here](https://github.com/emersion/go-smtp/blob/master/conn.go#L106) before going into the actual command handling.

**Comment by foxcpp** [comment]
This is intentional, some SMTP servers may make authentication optional. You are expected to track authentication status in your backend implementation and return ErrAuthRequired from MAIL/RCPT/DATA if it is actually required.

**Comment by mukulsib** [comment]
@foxcpp I completely understand the use case behind the optional auth but what is the need of having `AuthDisabled` as an option to server then
