### ISSUE TITLE
Allow backend to return an error on RCPT TO or MAIL FROM

### ISSUE THREAD

**Issue by emersion** [emersion/go-smtp#22]
We probably need to add a new type for transactions.

**Comment by foxcpp** [comment]
I propose to replace the User interface with the following Session interface:
```go
type Session interface {
  // Reset cleans Session state and prepares it to handle a new message.
  Reset()
  // MAIL FROM 
  SetFrom(s string) error
  // RCPT TO
  AddRcpt(s string) error
  // DATA
  Data(r io.Reader) error
}
```
And correspondigly change Backend inteface to return it instead of User.

What do you think?

**Comment by emersion** [comment]
There should be a "I'm done with this session, I won't use it anymore" function.

We should probably use the same names as the [`Client`](https://godoc.org/github.com/emersion/go-smtp#Client) interface for consistency.

I'm not a big fan of `Reset`, but it's not terrible either.

Your proposal looks overall good.

For reference, I had something among these lines locally:

```go
type User interface {
  NewTransaction() Transaction
  Logout() error
}

type Transaction interface {
  Mail(from string) error
  Rcpt(to string) error
  Data(r io.Reader) error
}
```

**Comment by emersion** [comment]
Having a single type as you proposed is probably better for the simplicity's sake.

**Comment by foxcpp** [comment]
Almost done with it, will send PR soon!

**Comment by foxcpp** [comment]
Not quite sure how to update backendutil.TransformBackend. 
I see two possible approaches:
* Buffer calls to Mail/Rcpt/Data, call Transform function on all data and pass fields to underlying backend
   - Simplicity
   - Underlying backend loses ability to report errors on From/Rcpt
* Split Transform function into separate TransformFrom, TransformTo, TransformData. Pass transformed data to underlying backend instantly.
  - Underlying backend does have an ability to report errors on From/Rcpt
  - Can't use From/To information in TransformData
* Drop TransformBackend altogether. Stateful nature of the new Session object makes it hard to use (limitations of above approaches).

What do you think is better? Or do you have other ideas?

**Comment by emersion** [comment]
I'm fine with dropping it.

Oh, and it would be nice to add a `type TransactionFunc func(from string, to []string, r io.Reader) error` (or `SessionFunc` depending on the wording) which implements `Transaction` (or `Session`). That would make it easy to upgrade and create backends that don't need this functionality.

**Comment by emersion** [comment]
Eh. I guess it's not possible because we need to keep some state.
