### ISSUE TITLE
What's the best way to check and enforce TLS connection?

### ISSUE THREAD

**Issue by iredmail** [emersion/go-smtp#227]
With v0.15.0, we check and enforce TLS connection in `Login()` and `AnonymouseLogin()`, with v0.16.0 and later, we do the same in `AuthPlain()` and `Mail()`.

There's a problem: `Login()` or `AuthPlain()` is called when client sends smtp directive `AUTH`, the smtp connection could be either insecure or secure (TLS). If it's insecure, the base64 encoded username/password in `AUTH` may be leaked. We want to check and enforce secure connection before `AUTH` command to prevent credential leak.

Question: what's the best way to check and enforce TLS with latest go-smtp v0.17.0? Is it better to add a new method for `smtp.Session` interface for this purpose before `AUTH`?

**Comment by emersion** [comment]
> We want to check and enforce secure connection before AUTH command to prevent credential leak.

That's the default behavior. `AllowInsecureAuth` will turn that off.

**Comment by iredmail** [comment]
If i understand the source code[1]  correctly, if `AllowInsecureAuth=false`, go-smtp disables `AUTH` but it continues the smtp session, right? What we want is terminating the smtp session instead.

https://github.com/emersion/go-smtp/blob/b4236a6d6ff4a5cd166ce0cec02b92c66f6dd3d0/conn.go#L253-L260

**Comment by emersion** [comment]
I don't understand why one would want to advertise AUTH while always sending an error while it's used.

**Comment by iredmail** [comment]
Misconfiguration.

**Comment by emersion** [comment]
Please elaborate... If I had to guess, is it to give users a clear error when they try to setup their client but forget to enable encryption?

**Comment by iredmail** [comment]
Hi @emersion 

Thanks for the patience and helping. 

Our smtp "clients" are multiple MTAs, not MUA. And we force secure smtp connection for secure traffic. If a client doesn't enable / establish secure connection, we reject and terminate the connection to prevent leaking credentials in AUTH directive until it's properly configured. 

In this case, AllowInsecureAuth is not the solution since it continues the session.

Maybe it's better to add some more methods to Session interface to allow developers to handle connection or data in different smtp state, for example:

- right after connection is established. This is the best state in smtp session to perform IP address or reverse hostname based whitelisting and blacklisting. 
- right after EHLO. Again, HELO hostname based white/blacklisting. 
- right after STARTTLS (it 's called no matter it's secure or insecure connection). Good state to check and enforce secure connection. 


Your opinion?

**Comment by iredmail** [comment]
@emersion Any update?

**Comment by emersion** [comment]
Right, thanks for explaining, that makes sense. I'd suggest:

- Set `AllowInsecureAuth = true`
- In the Backend's `NewSession` function, check whether the connection is TLS or not, store that info somewhere in the returned Session, and return an error in `AuthPlain`.

**Comment by iredmail** [comment]
> * In the Backend's `NewSession` function, check whether the connection is TLS or not, store that info somewhere in the returned Session, and return an error in `AuthPlain`.

Hi @emersion,

Thanks for the reply, but this suggestion won't work.

I tested this before created this issue, and double tested moment ago: it doesn't work with STARTTLS.
I used testing code like below:

```
func (b *Backend) NewSession(conn *smtp.Conn) (session smtp.Session, err error) {
	ip, _, _ := utils.GetIPPortFromNetAddr(conn.Conn().RemoteAddr())

	state, _ := conn.TLSConnectionState()
	fmt.Printf("DEBUG Version: [%s] %d", ip, state.Version)

	// ... omit other testing code here...
```

- When client establishes connection, the `state.Version` is 0 (which means insecure connection)
- Then client issues `STARTTLS` smtp directive in same smtp session, `NewSession` is called again(?) and `state.Version` is now `772` (TLSv1.3, cipher suite is TLS_AES_128_GCM_SHA256).

Since `NewSession` is called before `STARTTLS` directive, we cannot judge whether it's secure in this stage, and `smtp.Session` doesn't have a public method for starttls directive. So we still have to check this in `AuthPlain()` which may already leak the account credential sent by `AUTH` directive.

Can we add more public methods to `smtp.Session` to handle more smtp stages? e.g. before `AUTH`.

**Comment by emersion** [comment]
What you're asking for protocol-wise is not possible. Clients may send either `STARTTLS` or `AUTH` directly, and there is no way to know in advance. If the client decides to send `AUTH` without `STARTTLS`, the credentials are leaked.

The `AUTH` command contains an optional initial response argument, which in the case of PLAIN contains the username/password.

**Comment by iredmail** [comment]
ok, i will live with it. Thanks very much for helping. :)
