### ISSUE TITLE
Allow backend to return per-recipient information

### ISSUE THREAD

**Issue by emersion** [emersion/go-smtp#23]
e.g. success for recipient 1 and failure for recipient 2.

This is required for complete LMTP support. The client should also support this.

This could be done with a `LMTPError` implementing `error`.

**Comment by mschneider82** [comment]
I have implemented this using channels to wait for rcpt status, since the rcpt order needs to be the same as incoming, you can see the _test file for a example.

**Comment by mschneider82** [comment]
What do you think? I did many tests today works pretty good, also the cancel with ctx

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/go-smtp/pull/66
