### ISSUE TITLE
Request for opportunistic TLS support

### ISSUE THREAD

**Issue by lpar** [emersion/go-smtp#256]
With the removal of `StartTLS()`, it seems a bit painful to communicate with an SMTP server determined at run time, when it may or may not support STARTTLS.

I might be missing something, but it seems like you now need to connect, use `client.Extension("STARTTLS")` to see if the server supports STARTTLS, and then if it does you need to disconnect with `Close()` and start a new client and new connection using `NewClientStartTLS()` or `DialStartTLS()`.

I wondered if the client might support opportunistic use of STARTTLS, in which case I could enable STARTTLS every time and then check if it succeeded with `TLSConnectionState()`. Unfortunately it looks like if the client is set up with `DialStartTLS()` or `NewClientStartTLS()`, it demands STARTTLS or else it returns an error.

So, how about an option for opportunistic STARTTLS? Basically like `DialStartTLS()`/`NewClientStartTLS()`, but it carries on anyway if STARTTLS fails, and if TLS is important then it's up to the caller to check if it ended up enabled.

**Comment by emersion** [comment]
The original intention behind the recent changes is indeed to disallow opportunistic TLS. The motivation is that opportunistic TLS is as good as insecure plaintext, because it's trivial for a man-in-the-middle to filter out the STARTTLS extension.

What is your use-case?

**Comment by lpar** [comment]
The use case is software where the SMTP server is configured by end users at run time and the connection is typically on an internal network, where plain SMTP is often available.

Given plain SMTP as an option, users who don't know the details of SMTP will likely go with it. In which case, having STARTTLS encryption is arguably better than having none at all. Users who know what they're doing will go with implicit TLS / SMTPS.

Basically, if someone has configured plain unencrypted SMTP, I don't see that refusing to use STARTTLS opportunistically is a security improvement.

**Comment by emersion** [comment]
Sorry, but I disagree. Opportunistic TLS provides no substantial extra security over plaintext.

**Comment by greenpau** [comment]
I am also running into this issue. Upon upgrading, I have to rewrite this snippet.

```
    dial := smtp.Dial
    if e.Protocol == "smtps" {
        dial = func(addr string) (*smtp.Client, error) {
            return smtp.DialTLS(addr, nil)
        }
    }

    c, err := dial(e.Address)
    if err != nil {
        return err
    }
    defer c.Close()

    if found, _ := c.Extension("STARTTLS"); found {
        if err := c.StartTLS(nil); err != nil {
            return err
        }
    }
```

@emersion , do you have a pattern for rewriting exiting clients?

**Comment by greenpau** [comment]
> My recommendation is to always use STARTTLS, unless the user has explicitly requested to disable it.

@emersion , regardless of the extension?

**Comment by emersion** [comment]
Yes. As explained above, checking for the extension makes your program vulnerable to [downgrade attacks](https://en.wikipedia.org/wiki/Downgrade_attack).

**Comment by hochhaus** [comment]
> Opportunistic TLS provides no substantial extra security over plaintext.

@emersion Thanks for your comment here.

Can you clarify the goal of this package? Is (a subset of) the intent to support sending email to arbitrary SMTP servers on the internet? If so, plenty of SMTP servers in-the-wild still do not support TLS or support TLS only using self signed certs. To the best of my knowledge, folks using go-smtp for this purpose do not have an upgrade path to 0.21.0+.

This behavior in 0.21.0+ is unexpected to me given that without only supporting delivery to hosts with CA signed TLS certs the TLS certificate cannot be verified anyways. This means that when delivering to arbitrary SMTP servers on the internet it is necessary (for some servers) to pass InsecureSkipVerify to StartTLS(). In this mode, a threat model including a MITM stripping STARTTLS could instead simply accept a TLS connection using a self signed cert which also does not protect the data. Instead, in this context it seems that a major goal of opportunistic TLS is to prevent passive eavesdropping.

If the goal of this library is only to support delivery to a subset of well configured modern SMTP servers (such as MTA-STS (https://datatracker.ietf.org/doc/html/rfc8461) servers) then the current implementation makes a lot of sense and is more secure.

Would you consider an update which allows opportunistic TLS when delivering opted into be the calling code?

**Comment by emersion** [comment]
There is a difference between opportunistic TLS and self-signed/plaintext connections. It's perfectly possible to use self-signed certificates (via `tls.Config`) or plaintext connections (via `smtp.Dial`) with go-smtp. It's even possible to implement opportunistic TLS by trying STARTTLS first and falling back to plaintext, if you really want to. I don't believe SMTP servers are using self-signed certs in general.

No, sorry, I will not accept a new API for opportunistic TLS since it's insecure and possible to implement outside.

**Comment by hochhaus** [comment]
Thanks @emersion.

> There is a difference between opportunistic TLS and self-signed/plaintext connections.

Absolutely

> It's perfectly possible to use self-signed certificates (via `tls.Config`)

Agreed (and we have been doing so for some time)

> or plaintext connections (via `smtp.Dial`) with go-smtp.

Agreed

> It's even possible to implement opportunistic TLS by trying STARTTLS first and falling back to plaintext, if you really want to.

Our current limiting factor this approach is that we use a custom dialer and need to specify a custom `localName` (other than `localhost`) to keep some of the servers that we deliver email to happy. Therefore, we need to call an explicit `c.Hello(...)`. As best I can tell, this isn't possible with `smtp.NewClientStartTLS`.

Would you be open to a method allowing a custom `localName` via the `NewClientStartTLS` code path?

> I don't believe SMTP servers are using self-signed certs in general.

We are a small mailer (10s of thousands of emails / day) and we run into this frequently. If helpful, I can provide examples in a private setting.

**Comment by hochhaus** [comment]
> We are a small mailer (10s of thousands of emails / day) and we run into this frequently. If helpful, I can provide examples in a private setting.

Possibly related this [LE post from 2018](https://community.letsencrypt.org/t/lets-encrypt-for-smtp/66171) is old but it matches what we see in the wild today:

> Look at certificates out there used by major companies. Many are expired, many don’t match the hostname, many are self-signed. This is because SMTP does not care about the validity of the certificate. It simply doesn’t. The alternative the RFC requires is plain text, so using the public key from a problematic certificate is actually more secure than using plain text because there was a problem with the certificate.

**Comment by emersion** [comment]
> Would you be open to a method allowing a custom localName via the NewClientStartTLS code path?

This is by design, because anything transmitted over plaintext can be spoofed thus must not be relied on.

**Comment by hochhaus** [comment]
Thanks @emersion.

I appreciate your work with this package as well as all of your other open source work.

Unfortunately, these design decisions mean that `go-smtp` can't be used (unpatched) by code which need to be able to deliver emails to arbitrary SMTP servers on the internet.
