### ISSUE TITLE
EHLO after RSET

### ISSUE THREAD

**Issue by sapmli** [emersion/go-smtp#269]
Currently, go-smtp starts a new session for every EHLO command it receives.
So, any user information, e.g. from AUTH LOGIN, gets lost.

[RFC 5321](https://datatracker.ietf.org/doc/html/rfc5321#section-4.1.4) states:
> An EHLO command MAY be issued by a client later in the session.  If
   it is issued after the session begins and the EHLO command is
   acceptable to the SMTP server, the SMTP server MUST clear all buffers
   and reset the state exactly as if a RSET command had been issued.  In
   other words, the sequence of RSET followed immediately by EHLO is
   redundant, but not harmful other than in the performance cost of
   executing unnecessary commands.

Probably this means the new EHLO argument should be handed over to an existing session, instead of starting a new session. Clients may issue an EHLO after RSET, to set a different client information for the next mail in the same connection.

It's currently also not possible to send a new EHLO after RSET in outgoing connections using the [SMTP client](https://github.com/emersion/go-smtp/blob/master/client.go#L204-L212).

**Comment by emersion** [comment]
Indeed, seems like `Conn.reset()` should be used instead of creating a new session if we already have one.
