### ISSUE TITLE
Enhanced Status Codes support

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-smtp#36]
- [x] Add EnhancedCode field to SMTPError (`[3]uint`?)
- [ ] ~~Client: Parse enhanced codes~~
- [x] Server: Add capability "ENHANCEDSTATUSCODES" (#37)
- [x] Server: Set X.0.0 (X is based on class) if returned error lacks explicit code
- [x] Server: Send enhanced codes (#37)

**Comment by emersion** [comment]
* RFC: https://tools.ietf.org/html/rfc3463
* IANA registry: https://www.iana.org/assignments/smtp-enhanced-status-codes/smtp-enhanced-status-codes.xhtml

I'd prefer to have enums for those.

**Comment by foxcpp** [comment]
#37
