### ISSUE TITLE
DATA phase always calls client reset?

### ISSUE THREAD

**Issue by tuck1s** [emersion/go-smtp#40]
https://github.com/emersion/go-smtp/blob/930d6dfbf447707ddcc38bbafccd8d1596cc6181/conn.go#L470

Is it expected that every DATA phase always calls client reset? Or should this be just for certain circumstances. Commenting this line out seems to work fine via the client sending QUIT.

This may be helpful/relevant: https://stackoverflow.com/a/25023155/8545455
Disclosure: I haven't read the latest SMTP specs!

**Comment by emersion** [comment]
>Is it expected that every DATA phase always calls client reset?

Yes. The `DATA` command resets the session state.
