### ISSUE TITLE
Implement AUTH LOGIN method

### ISSUE THREAD

**Issue by tuck1s** [emersion/go-smtp#41]
Some thoughts on adding server support for this.

The server code already supports the PLAIN method described in https://tools.ietf.org/html/rfc4954#section-4.1
however https://tools.ietf.org/html/rfc4422#section-3 is also relevant.

Client `swaks` is liberal in using whichever PLAIN or LOGIN auth methods the server offers.
Some clients (e.g. Windows PowerShell `Send-MailMessage`) cannot use PLAIN (according to tests I've tried).

Adding a `sasl.Login` entry to `func NewServer` in `server.go` achieves most of what's needed. Then we interwork with clients such as `swaks`.
This is because `swaks` chooses to send the basic `LOGIN` command form (without username) then await the server's challenge response.

Aforementioned Windows client chooses to always send the `LOGIN base64username` form. This is not currently handled by `go-sasl/login.go` `func Next`, because it always begins in the `loginNotStarted` state, ignoring the already provided username, and proceeds to challenge for it.

https://github.com/emersion/go-sasl/blob/7e096a0a6197b89989e8cc31016daa67c8c62051/login.go#L32

Ideally we support both LOGIN formats. I'm happy to do the work. I just had a question of style for you -

a) make `go-sasl/login.go Next` be aware of the presence of an initial `response` value, assume this is the username, and go straight to `loginWaitingPassword`

or 
b) add conditional logic to https://github.com/emersion/go-smtp/blob/469c269417f0204740f34158e7e976708ea25549/conn.go#L359 to explicitly call `Next` one time before entering the `for` loop

b) limits scope of change to just this repo; but perhaps it's better to improve `Next` to handle RFC4422 sec 3 fully. 

See also
https://www.jetmore.org/john/code/swaks/latest/doc/ref.txt
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-6

**Comment by tuck1s** [comment]
Here's how a) would look
```
func (a *loginServer) Next(response []byte) (challenge []byte, done bool, err error) {
	switch a.state {
	case loginNotStarted:
		// Check for initial response field, as per RFC4422 section 3
		if response == nil {
			challenge = []byte("Username:")
		} else {
			a.username = string(response)
			challenge = []byte("Password:")
			a.state++
		}
	case loginWaitingUsername:
		a.username = string(response)
		challenge = []byte("Password:")
	case loginWaitingPassword:
		a.password = string(response)
		err = a.authenticate(a.username, a.password)
		done = true
	default:
		err = ErrUnexpectedClientResponse
	}

	a.state++
	return
}
```

**Comment by emersion** [comment]
>Here's a first cut at a)

This looks okay to me (it could use a `fallthrough`).

>perhaps it's better to improve Next to handle RFC4422 sec 3 fully.

Agreed. What's missing exactly?

**Comment by tuck1s** [comment]
> This looks okay to me (it could use a `fallthrough`).
Can I fallthrough only if `response` is non-nil? We need to preserve that existing behaviour

> Agreed. What's missing exactly?

The `else` clause is new, that serves to handle the `LOGIN base64blah` case which is not currently handled.

Also I'm aware I'm adding more conditions to your code .. I'd should figure out how to add some cases in your codecov , hate to see the %age cover reducing.

**Comment by emersion** [comment]
>Yep .. have to add a break to the nil case, to ensure we skip out, and keep the ++ so we end up in loginWaitingPassword next time

Can you submit this as a pull request?

>Also I'm aware I'm adding more conditions to your code .. I'd should figure out how to add some cases in your codecov , hate to see the %age cover reducing.

No worries. To improve the test coverage you just need to add more tests (e.g. add a test that checks that swaks authentication works).

**Comment by tuck1s** [comment]
Given #42 isn't the right way to go - could you provide an example of how to call `s.EnableAuth` as a library user? I couldn't see any examples, it seems a bit different to doing this from within the library like #42 tried to do.

I'm trying to do
```
	s := smtp.NewServer(be)

	// Add LOGIN auth method as Windows Send-MailMessage client requires it
	s.EnableAuth(sasl.Login, func(conn *Conn) sasl.Server {
		return sasl.NewLoginServer(func(username, password string) error {
			state := conn.State()
			session, err := be.Login(&state, username, password)
			if err != nil {
				return err
			}

			conn.SetSession(session)
			return nil
		}))
		)
```
however `Conn`, `State` and `SetSession` are not externally accessible.

**Comment by foxcpp** [comment]
Probably it would be a good idea to provide helper function for this in go-smtp.
```go 
s.EnableAuth(sasl.Login, smtp.AuthLogin)
```

**Comment by emersion** [comment]
>Given #42 isn't the right way to go - is this the right approach outside the library? Seems to work :-)

Yeah

>Probably it would be a good idea to provide helper function for this in go-smtp.

Nah, I don't want to make it easier to enable deprecated features. Clients should be fixed to use PLAIN instead.

**Comment by tuck1s** [comment]
The LOGIN mechanism does indeed seem to be marked as obsolete in the list that https://tools.ietf.org/html/rfc4422 refers out to,  here:

https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml

Seems like Windows is definitely a laggard in not implementing `PLAIN` in `Send-MailMessage` commandlet.

**Comment by emersion** [comment]
Yeah, thanks for checking.

I believe we can close this issue now.
