### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by buzai** [emersion/go-smtp#5]
smtp server is only to send email?
if i want to have some users and password i must have some code with a mysql to manage the user?

**Comment by emersion** [comment]
>smtp server is only to send email?

Yes. IMAP is for receiving emails.

>if i want to have some users and password i must have some code with a mysql to manage the user?

Yes. Implement the backend interface, there's a basic example in the README.

**Comment by buzai** [comment]
thanck u
