### ISSUE TITLE
SMTPUTF8 capability

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-smtp#67]
I believe most backend implementations could handle UTF-8 addresses and MIME headers just fine, so it is a good idea to tell clients that we are fine with UTF-8.

Also I think we should tell the backend that SMTPUTF8 support was requested (through MAIL argument). This way it can make decision on whether it can actually handle the message (say, if it implements transparent forwarding and upstream server doesn't support SMTPUTF8).

References:
- SMTP Extension for SMTPUTF8: https://tools.ietf.org/html/rfc6531
- Internationalized Email Headers: https://tools.ietf.org/html/rfc6532

**Comment by foxcpp** [comment]
>An SMTPUTF8-aware SMTP client MUST NOT send an internationalized message to an SMTP server that does not support SMTPUTF8. If the SMTP server does not support this option, then the SMTPUTF8-aware SMTP client has three choices according to Section 3.2 of this specification. 

Basically, server MAY transform the message, if for whatever reason it doesn't do that - it should reject it (by generating NDN, in your case).

**Comment by emersion** [comment]
Hmm, transforming the message will break DKIM…

**Comment by foxcpp** [comment]
>Hmm, transforming the message will break DKIM…

Sure it will, that's why servers usually don't do it.
