### ISSUE TITLE
Relationship with net/smtp

### ISSUE THREAD

**Issue by bergwerf** [emersion/go-smtp#83]
I'm sorry if I am reading over something, but it seems a lot of this library is exactly the same as `net/smtp`. What is the difference, and in which scenarios is `net/smtp` not sufficient? Thanks :)

**Comment by foxcpp** [comment]
net/smtp is "frozen" and not getting any new features. go-smtp includes server implementation and a number of improvements over net/smtp for client (including ability to use SMTPUTF8 and some other extensions).
