### ISSUE TITLE
Returning MessageId in 200 OK Response

### ISSUE THREAD

**Issue by kingster** [emersion/go-smtp#86]
Hi

Today when the message gets queued we send response `250 2.0.0 OK: queued`.  Other smtp servers returns a messageId to help the client's track the request later, eg:  google does `250 2.0.0 OK  1571601091 d44si1315748ede.149 - gsmtp`

How to implement the same ?

I see this option in `conn.go`

```go
func (c *Conn) handleData(arg string) {
....
code, enhancedCode, msg := toSMTPStatus(c.Session().Data(r))
```
Split this into two

```go
msg, err := c.Session().Data(r)
code, enhancedCode, msg := toSMTPStatus(err, msg)
```

But this breaks the signature of `Session`. What would you suggest in this? What are the other ways to achieve this?

**Comment by emersion** [comment]
You can return a custom code and message with [`SMTPError`](https://godoc.org/github.com/emersion/go-smtp#SMTPError)

**Comment by kingster** [comment]
Thanks! It works
