### ISSUE TITLE
client: Add I/O timeouts

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-smtp#88]
RFC 5321:
>4.5.3.2.  Timeouts
>
>   An SMTP client MUST provide a timeout mechanism.  It MUST use per-
>   command timeouts rather than somehow trying to time the entire mail
>   transaction.  Timeouts SHOULD be easily reconfigurable, preferably
>   without recompiling the SMTP code.

**Comment by emersion** [comment]
We probably want to set some sane defaults.

**Comment by foxcpp** [comment]
RFC 5321 provides recommended minimal timeouts

**Comment by foxcpp** [comment]
I wonder if this could be implemented by adding context.Context support for client (#19).
