### ISSUE TITLE
minor release needed

### ISSUE THREAD

**Issue by PaluMacil** [emersion/go-smtp#93]
hello, I would like to recommend that a minor release be made. From reading about the 2 commits besides the README tweaks since the last release, I see that there is both a race condition as well as a security issue fixed. Are there any other steps that need to be taken first? PR 72 also looks pretty critical to merge, though I see it shows a failed status due to a very small decrease in code coverage. It would be great to see that slip into the patch release.

**Comment by foxcpp** [comment]
I will submit another small PR shortly that fixes minor SASL-related issue in server code. Note that while using Go modules you can always select a particular commit and not only tagged release. e.g.
```
go get github.com/emersion/go-smtp@master
```

**Comment by PaluMacil** [comment]
Thanks!

While _technically_ selecting a commit after making an explicit decision is similar to waiting for a minor release, it still feels a lot better to use tagged versions.

**Comment by emersion** [comment]
Released 0.13.0.
